### ISSUE TITLE
not work - nothing changed after install

### ISSUE THREAD

**Issue by errogaht** [hirak/prestissimo#137] opened 2017-03-05 06:14 UTC
Hello! Great idea, thanks for your work, but it not work.
1. composer global require "hirak/prestissimo:^0.3"
2. composer update
3. see just regular composer work, nothing improved, no parralell installing

**Comment by desh901** [comment] 2017-03-07 10:51
Same here!

**Comment by itsnotvalid** [comment] 2017-03-21 11:08
Confirmed with composer 1.4.1 .

**Comment by nntoan** [comment] 2017-03-25 17:45
Anyone know how this plugin works? Because I don't see the differencet installation like GIF image in README.md of this project. (Using 1.4.1)

**Comment by errogaht** [comment] 2017-03-26 07:15
me too, please tell us how to

**Comment by SvenRtbg** [comment] 2017-03-27 15:47
The plugin does not INSTALL in parallel, only downloads in parallel. And if the package is already in the local Composer cache, it needs no download, so the plugin cannot do anything.

I suppose that by running `composer update` you don't get any updates. Please provide some more details, like the output of your shell, when running the command. Currently your issue really is "it doesn't work, but I won't show what I did". Nobody can help with that few information.

**Comment by o5** [comment] 2017-04-05 09:27
I also think there is something wrong now.

```bash
[root@4611fc7a5b8c ~]# php -v
PHP 7.1.3 (cli) (built: Mar 19 2017 15:31:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

[root@4611fc7a5b8c ~]# composer --version
Composer version 1.4.1 2017-03-10 09:29:45

[root@4611fc7a5b8c ~]# composer global show hirak/prestissimo
Changed current directory to /root/.composer
name     : hirak/prestissimo
descrip. : composer parallel install plugin
keywords : install, parallel, speedup
versions : * 0.3.5
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/hirak/prestissimo.git abfc45c609b049c488f894251d2ea4a4e4bfa01e
dist     : [zip] https://api.github.com/repos/hirak/prestissimo/zipball/abfc45c609b049c488f894251d2ea4a4e4bfa01e abfc45c609b049c488f894251d2ea4a4e4bfa01e
names    : hirak/prestissimo

autoload
psr-4
Hirak\Prestissimo\ => src/

requires
composer-plugin-api ^1.0.0
ext-curl *
php ^5.3.2 || ^7.0

requires (dev)
composer/composer 1.0.0
phpunit/phpunit ^4.8
squizlabs/php_codesniffer ^2.5

[root@7f2a66ce23a3 ~]# composer create-project laravel/laravel laravel1 --no-progress --profile --prefer-dist
[88.9MB/5.40s] Installing laravel/laravel (v5.4.16)
[88.9MB/5.41s]   - Installing laravel/laravel (v5.4.16): [88.9MB/5.41s] Downloading[88.9MB/7.52s]  (100%)[89.1MB/7.59s]
[88.9MB/7.75s] Created project in laravel1
[89.9MB/8.08s] > php -r "file_exists('.env') || copy('.env.example', '.env');"
[6.9MB/10.47s] Loading composer repositories with package information
[7.2MB/10.79s] Updating dependencies (including require-dev)
[170.6MB/16.59s] Package operations: 59 installs, 0 updates, 0 removals
[170.6MB/16.59s]   - Installing symfony/polyfill-mbstring (v1.3.0): [170.6MB/16.59s] Downloading[170.6MB/17.58s]  (100%)[170.7MB/17.62s]
[170.6MB/17.62s]   - Installing symfony/var-dumper (v3.2.6): [170.6MB/17.63s] Downloading[170.6MB/18.74s]  (100%)[170.7MB/18.76s]
[170.6MB/18.77s]   - Installing jakub-onderka/php-console-color (0.1): [170.6MB/18.77s] Downloading[170.6MB/19.68s]  (100%)[170.7MB/19.69s]
[170.6MB/19.69s]   - Installing jakub-onderka/php-console-highlighter (v0.3.2): [170.6MB/19.69s] Downloading[170.6MB/20.59s]  (100%)[170.7MB/20.60s]
[170.6MB/20.60s]   - Installing dnoegel/php-xdg-base-dir (0.1): [170.6MB/20.60s] Downloading[170.6MB/21.51s]  (100%)[170.7MB/21.52s]
[170.6MB/21.52s]   - Installing nikic/php-parser (v3.0.5): [170.6MB/21.52s] Downloading[170.6MB/23.12s]  (100%)[170.8MB/23.18s]
[170.6MB/23.18s]   - Installing psr/log (1.0.2): [170.6MB/23.21s] Downloading[170.6MB/24.11s]  (100%)[170.7MB/24.12s]
[170.6MB/24.12s]   - Installing symfony/debug (v3.2.6): [170.6MB/24.12s] Downloading[170.6MB/25.20s]  (100%)[170.7MB/25.21s]
[170.6MB/25.22s]   - Installing symfony/console (v3.2.6): [170.6MB/25.22s] Downloading[170.6MB/26.70s]  (100%)[170.8MB/26.75s]
[170.6MB/26.75s]   - Installing psy/psysh (v0.8.3): [170.6MB/26.75s] Downloading[170.6MB/28.14s]  (100%)[170.7MB/28.16s]
[170.6MB/28.16s]   - Installing vlucas/phpdotenv (v2.4.0): [170.6MB/28.16s] Downloading[170.6MB/29.07s]  (100%)[170.7MB/29.08s]
[170.6MB/29.08s]   - Installing symfony/css-selector (v3.2.6): [170.6MB/29.08s] Downloading[170.6MB/30.16s]  (100%)[170.7MB/30.18s]
[170.6MB/30.18s]   - Installing tijsverkoyen/css-to-inline-styles (2.2.0): [170.6MB/30.18s] Downloading[170.6MB/31.08s]  (100%)[170.7MB/31.09s]
[170.6MB/31.09s]   - Installing symfony/routing (v3.2.6): [170.6MB/31.09s] Downloading[170.6MB/32.38s]  (100%)[170.8MB/32.40s]
[170.6MB/32.40s]   - Installing symfony/process (v3.2.6): [170.6MB/32.40s] Downloading[170.6MB/33.49s]  (100%)[170.8MB/33.50s]
[170.6MB/33.50s]   - Installing symfony/http-foundation (v3.2.6): [170.6MB/33.51s] Downloading[170.6MB/34.89s]  (100%)[170.9MB/34.91s]
[170.6MB/34.91s]   - Installing symfony/event-dispatcher (v3.2.6): [170.6MB/34.91s] Downloading[170.6MB/35.90s]  (100%)[170.8MB/35.92s]
[170.6MB/35.92s]   - Installing symfony/http-kernel (v3.2.6): [170.6MB/35.92s] Downloading[170.6MB/37.42s]  (100%)[170.9MB/37.45s]
[170.6MB/37.45s]   - Installing symfony/finder (v3.2.6): [170.6MB/37.45s] Downloading[170.7MB/38.54s]  (100%)[170.7MB/38.60s]
[170.6MB/38.61s]   - Installing swiftmailer/swiftmailer (v5.4.6): [170.6MB/38.61s] Downloading[170.7MB/40.44s]  (100%)[170.8MB/40.49s]
[170.6MB/40.50s]   - Installing paragonie/random_compat (v2.0.10): [170.6MB/40.50s] Downloading[170.7MB/41.51s]  (100%)[170.7MB/41.52s]
[170.6MB/41.53s]   - Installing ramsey/uuid (3.6.1): [170.7MB/41.53s] Downloading[170.7MB/42.62s]  (100%)[170.7MB/42.64s]
[170.7MB/42.64s]   - Installing symfony/translation (v3.2.6): [170.7MB/42.64s] Downloading[170.7MB/43.92s]  (100%)[170.9MB/43.95s]
[170.7MB/43.96s]   - Installing nesbot/carbon (1.22.1): [170.7MB/43.96s] Downloading[170.7MB/45.04s]  (100%)[170.7MB/45.06s]
[170.7MB/45.06s]   - Installing mtdowling/cron-expression (v1.2.0): [170.7MB/45.06s] Downloading[170.7MB/46.55s]  (100%)[170.7MB/46.56s]
[170.7MB/46.56s]   - Installing monolog/monolog (1.22.1): [170.7MB/46.56s] Downloading[170.7MB/47.97s]  (100%)[170.7MB/48.01s]
[170.7MB/48.02s]   - Installing league/flysystem (1.0.37): [170.7MB/48.02s] Downloading[170.7MB/49.02s]  (100%)[170.7MB/49.04s]
[170.7MB/49.04s]   - Installing erusev/parsedown (1.6.2): [170.7MB/49.04s] Downloading[170.7MB/50.12s]  (100%)[170.7MB/50.14s]
[170.7MB/50.14s]   - Installing doctrine/inflector (v1.1.0): [170.7MB/50.14s] Downloading[170.7MB/51.03s]  (100%)[170.7MB/51.04s]
[170.7MB/51.05s]   - Installing laravel/framework (v5.4.17): [170.7MB/51.05s] Downloading[170.7MB/53.37s]  (100%)[170.7MB/53.45s]
[170.7MB/53.47s]   - Installing laravel/tinker (v1.0.0): [170.7MB/53.47s] Downloading[170.7MB/54.63s]  (100%)[170.7MB/54.64s]
[170.7MB/54.65s]   - Installing fzaninotto/faker (v1.6.0): [170.7MB/54.65s] Downloading[170.7MB/58.71s]  (100%)[170.8MB/58.82s]
[170.7MB/58.83s]   - Installing hamcrest/hamcrest-php (v1.2.2): [170.7MB/58.83s] Downloading[170.7MB/60.18s]  (100%)[170.8MB/60.21s]
[170.7MB/60.22s]   - Installing mockery/mockery (0.9.9): [170.7MB/60.22s] Downloading[170.7MB/61.62s]  (100%)[170.8MB/61.65s]
[170.7MB/61.65s]   - Installing symfony/yaml (v3.2.6): [170.7MB/61.65s] Downloading[170.7MB/62.75s]  (100%)[170.8MB/62.76s]
[170.7MB/62.77s]   - Installing sebastian/version (2.0.1): [170.7MB/62.77s] Downloading[170.7MB/63.66s]  (100%)[170.7MB/63.67s]
[170.7MB/63.67s]   - Installing sebastian/resource-operations (1.0.0): [170.7MB/63.67s] Downloading[170.7MB/64.57s]  (100%)[170.7MB/64.58s]
[170.7MB/64.59s]   - Installing sebastian/recursion-context (2.0.0): [170.7MB/64.59s] Downloading[170.7MB/65.49s]  (100%)[170.8MB/65.50s]
[170.7MB/65.50s]   - Installing sebastian/object-enumerator (2.0.1): [170.7MB/65.50s] Downloading[170.7MB/66.38s]  (100%)[170.8MB/66.40s]
[170.7MB/66.40s]   - Installing sebastian/global-state (1.1.1): [170.7MB/66.40s] Downloading[170.7MB/67.40s]  (100%)[170.8MB/67.42s]
[170.7MB/67.44s]   - Installing sebastian/exporter (2.0.0): [170.7MB/67.44s] Downloading[170.7MB/68.35s]  (100%)[170.8MB/68.36s]
[170.7MB/68.37s]   - Installing sebastian/environment (2.0.0): [170.7MB/68.37s] Downloading[170.7MB/69.31s]  (100%)[170.8MB/69.33s]
[170.7MB/69.33s]   - Installing sebastian/diff (1.4.1): [170.7MB/69.34s] Downloading[170.7MB/70.34s]  (100%)[170.8MB/70.35s]
[170.7MB/70.35s]   - Installing sebastian/comparator (1.2.4): [170.7MB/70.35s] Downloading[170.7MB/71.35s]  (100%)[170.8MB/71.37s]
[170.7MB/71.38s]   - Installing doctrine/instantiator (1.0.5): [170.7MB/71.38s] Downloading[170.7MB/72.38s]  (100%)[170.8MB/72.39s]
[170.7MB/72.39s]   - Installing phpunit/php-text-template (1.2.1): [170.7MB/72.39s] Downloading[170.7MB/73.32s]  (100%)[170.7MB/73.33s]
[170.7MB/73.33s]   - Installing phpunit/phpunit-mock-objects (3.4.3): [170.7MB/73.33s] Downloading[170.7MB/74.52s]  (100%)[170.8MB/74.59s]
[170.7MB/74.62s]   - Installing phpunit/php-timer (1.0.9): [170.7MB/74.62s] Downloading[170.7MB/75.53s]  (100%)[170.8MB/75.54s]
[170.7MB/75.55s]   - Installing phpunit/php-file-iterator (1.4.2): [170.7MB/75.55s] Downloading[170.7MB/76.47s]  (100%)[170.8MB/76.48s]
[170.7MB/76.49s]   - Installing sebastian/code-unit-reverse-lookup (1.0.1): [170.7MB/76.49s] Downloading[170.7MB/77.38s]  (100%)[170.8MB/77.40s]
[170.7MB/77.40s]   - Installing phpunit/php-token-stream (1.4.11): [170.7MB/77.40s] Downloading[170.7MB/78.40s]  (100%)[170.8MB/78.41s]
[170.7MB/78.42s]   - Installing phpunit/php-code-coverage (4.0.8): [170.7MB/78.42s] Downloading[170.7MB/79.94s]  (100%)[170.8MB/79.97s]
[170.7MB/79.98s]   - Installing webmozart/assert (1.2.0): [170.7MB/79.98s] Downloading[170.7MB/80.96s]  (100%)[170.8MB/80.98s]
[170.7MB/80.98s]   - Installing phpdocumentor/reflection-common (1.0): [170.7MB/80.98s] Downloading[170.7MB/81.92s]  (100%)[170.8MB/81.94s]
[170.7MB/81.94s]   - Installing phpdocumentor/type-resolver (0.2.1): [170.7MB/81.94s] Downloading[170.7MB/82.92s]  (100%)[170.8MB/82.94s]
[170.7MB/82.94s]   - Installing phpdocumentor/reflection-docblock (3.1.1): [170.7MB/82.94s] Downloading[170.7MB/84.13s]  (100%)[170.8MB/84.16s]
[170.7MB/84.16s]   - Installing phpspec/prophecy (v1.7.0): [170.7MB/84.16s] Downloading[170.7MB/85.43s]  (100%)[170.8MB/85.45s]
[170.7MB/85.46s]   - Installing myclabs/deep-copy (1.6.0): [170.7MB/85.46s] Downloading[170.7MB/86.54s]  (100%)[170.8MB/86.55s]
[170.7MB/86.55s]   - Installing phpunit/phpunit (5.7.19): [170.7MB/86.56s] Downloading[170.7MB/88.13s]  (100%)[171.0MB/88.20s]
[147.0MB/88.42s] symfony/var-dumper suggests installing ext-symfony_debug ()
[147.0MB/88.42s] symfony/console suggests installing symfony/filesystem ()
[147.0MB/88.42s] psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
[147.0MB/88.42s] psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
[147.0MB/88.42s] symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
[147.0MB/88.42s] symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
[147.0MB/88.42s] symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
[147.0MB/88.42s] symfony/routing suggests installing symfony/expression-language (For using expression matching)
[147.0MB/88.42s] symfony/event-dispatcher suggests installing symfony/dependency-injection ()
[147.0MB/88.42s] symfony/http-kernel suggests installing symfony/browser-kit ()
[147.0MB/88.42s] symfony/http-kernel suggests installing symfony/class-loader ()
[147.0MB/88.42s] symfony/http-kernel suggests installing symfony/config ()
[147.0MB/88.42s] symfony/http-kernel suggests installing symfony/dependency-injection ()
[147.0MB/88.42s] paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
[147.0MB/88.42s] ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
[147.0MB/88.42s] ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
[147.0MB/88.42s] ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
[147.0MB/88.42s] ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
[147.0MB/88.42s] ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
[147.0MB/88.42s] ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
[147.0MB/88.42s] symfony/translation suggests installing symfony/config ()
[147.0MB/88.42s] monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
[147.0MB/88.42s] monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
[147.0MB/88.42s] monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
[147.0MB/88.42s] monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
[147.0MB/88.42s] monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
[147.0MB/88.42s] monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
[147.0MB/88.42s] monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
[147.0MB/88.42s] monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
[147.0MB/88.42s] monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
[147.0MB/88.42s] monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
[147.0MB/88.42s] monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
[147.0MB/88.42s] league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
[147.0MB/88.42s] laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
[147.0MB/88.42s] laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.5).)
[147.0MB/88.42s] laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
[147.0MB/88.42s] laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
[147.0MB/88.42s] laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
[147.0MB/88.42s] laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
[147.0MB/88.42s] laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
[147.0MB/88.42s] laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
[147.0MB/88.42s] laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
[147.0MB/88.42s] laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.2).)
[147.0MB/88.42s] laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
[147.0MB/88.42s] sebastian/global-state suggests installing ext-uopz (*)
[147.0MB/88.42s] phpunit/phpunit-mock-objects suggests installing ext-soap (*)
[147.0MB/88.42s] phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
[147.0MB/88.42s] phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
[147.0MB/88.42s] phpunit/phpunit suggests installing ext-xdebug (*)
[147.4MB/88.42s] Writing lock file
[147.4MB/88.42s] Generating autoload files
[147.8MB/88.55s] > Illuminate\Foundation\ComposerScripts::postUpdate
[148.7MB/88.57s] > php artisan optimize
[148.7MB/88.77s] Generating optimized class loader[148.7MB/88.77s]
[148.7MB/90.64s] The compiled services file has been removed.
[149.1MB/90.81s] > php artisan key:generate
[149.1MB/90.95s] Application key [base64:MnKugavMJR6d3oeAnRsq8jjc1zJBmixLbJnXbGOk8xs=] set successfully.[149.1MB/90.95s]
[149.1MB/90.96s] Memory usage: 149.06MB (peak: 175.86MB), time: 90.96s
```

So as you can see, there is no "pre-fetching" info.

**Comment by johnpbloch** [comment] 2017-04-07 15:28
Can confirm what @o5 reports. Here's a gist of my output: https://gist.github.com/johnpbloch/7803ebb2f9417257e082d7335a413b87

I even cleared the composer cache too, just in case.

**Comment by hirak** [comment] 2017-04-14 09:16
@errogaht I found some bug. Please try 0.3.6.

**Comment by errogaht** [comment] 2017-04-17 07:04
@hirak still not work... windows 10 PHP 7.0.8 Composer version 1.4.1 2017-03-10 09:29:45
```shell
composer global remove hirak/prestissimo (0.3.5 uninstalled)
composer global require hirak/prestissimo (0.3.6 installed)
```
![https://goo.gl/6Yts1X](https://goo.gl/6Yts1X)

**Comment by daften** [comment] 2017-05-05 13:02
Same issue on our build server with php 5.6.30 and composer 1.4.1. It works locally.
It seems CurlMulti doesn't return any URL's in the $result array on https://github.com/hirak/prestissimo/blob/master/src/Prefetcher.php#L35

**Comment by o5** [comment] 2017-05-19 12:24
It works with old version of `hirak/prestissimo` = `0.3.0`

**Comment by daften** [comment] 2017-05-19 13:11
@o5 we tried that and that was not a solution for us unfortunately

**Comment by diego-vieira** [comment] 2017-05-22 07:48
Confirmed that @o5 solution works, just install version 0.3.4.
```
composer global require hirak/prestissimo:0.3.4
```

test with
```
composer clear-cache
composer create-project laravel/laravel laravel1 --no-progress --profile --prefer-dist
```

**Comment by o5** [comment] 2017-05-23 07:49
@diego-vieira where did you tried? It's weird because now I'm trying this in our Docker CentOS-7 base image and it does not work! It works only on my Macbook, same version of php, composer, hirak/prestissimo on centos does not work. OMG

**Comment by diego-vieira** [comment] 2017-05-23 08:50
both on my macos sierra and [php 7 image](https://hub.docker.com/_/php/)

**Comment by fede91it** [comment] 2017-05-25 16:59
Also for me 0.3.6 doesn't work but 0.3.4 yes.
Windows 10 x64

**Comment by nntoan** [comment] 2017-05-26 04:08
0.3.4 works for me!
Ubuntu 16.04.2

Thanks for your workaround @o5

**Comment by hirak** [comment] 2017-05-27 05:31
I created prestissimo v0.3.7. If any error occurs, the error should be displayed, so please report it to me.

**Comment by errogaht** [comment] 2017-05-27 07:25
composer create-project laravel/laravel laravel1 --no-progress --profile --prefer-dist
with prestissimo 247 sec (0.3.7)
without prestissimo 236 seconds

windows 10
before each installs `composer clearchache`

**Comment by nntoan** [comment] 2017-05-27 09:03
I can confirm that benchmark from @errogaht . Prestissimo newer version slower than without prestissimo :(

**Comment by ashatrov-propertyfinder** [comment] 2017-06-08 12:55
Nothing changed after installing.
`php composer.phar install  --no-progress --profile --prefer-dist` does the same job with/without this plugin.
Same with v0.3.4 and v0.3.7 on PHP7.0.16 + composer 1.4.2

**Comment by ashatrov** [comment] 2017-06-08 13:01
Nothing changed after installing.
`php composer.phar install --no-progress --profile --prefer-dist` does the same job with/without this plugin.
Same with v0.3.4 and v0.3.7 on PHP7.0.16 + composer 1.4.2

**Comment by o5** [comment] 2017-06-27 09:34
I spent my 3hours and I finally catch it! 

It is **NOT** about version of `hirak/prestissimo`! It's about version of `curl`!! Official `CentOS 7` docker image has [`7.29.0`](https://curl.haxx.se/docs/releases.html) (more than 4years old!). If I update to latest curl it works like a charm! So probably it does not work in CentOS from [Fri Nov 25 15:56:44 UTC 2016](https://lists.centos.org/pipermail/centos-cr-announce/2016-November/003582.html). 

For CentOS users, there is link [How to upgrade Curl to the latest version](https://support.plesk.com/hc/en-us/articles/214029229-How-to-upgrade-Curl-to-the-latest-version-). I didn't try it, but Ubuntu has `7.47.0` and this version should work (as @nntoan [said](https://github.com/hirak/prestissimo/issues/137#issuecomment-304186064)).

**Comment by emirb** [comment] 2017-07-14 15:06
Thanks @o5

**Comment by lucasmezencio** [comment] 2017-08-24 14:25
@hirak any news on this?

**Comment by o5** [comment] 2017-08-24 14:40
@errogaht: Please close this issue. I think there is no problem with prestissimo.

**Comment by emirb** [comment] 2017-08-24 15:11
@o5 True, it's rather an outdated curl problem.

**Comment by nntoan** [comment] 2017-08-25 02:50
I think this issue can be safely closed. It's working finally :)

**Comment by daften** [comment] 2017-08-28 08:14
I think before closing, documentation should be updated with what @o5 found!

**Comment by errogaht** [comment] 2018-02-21 18:48
Work for me too! Thank you! Great speed improvement!

**Closed** 2018-02-21 18:47 UTC

**Comment by seyfer** [comment] 2019-04-17 09:35
Is this connected? https://github.com/hirak/prestissimo/issues/149

but Curl version is fresh and package also latest
```
curl --version
curl 7.52.1
```

**Comment by sinamiandashti** [comment] 2020-06-25 12:15
for me it was --no-plugin shit flag in composer install
